# Generated by Django 4.1.3 on 2022-12-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedagog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('data_roj', models.DateField(verbose_name='Дата')),
                ('adres', models.TextField(verbose_name='Адрес')),
                ('snils', models.CharField(max_length=100, verbose_name='СНИЛС')),
                ('telefon', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ser_pas', models.CharField(max_length=200, verbose_name='Серия паспорта')),
                ('nom_pas', models.CharField(max_length=200, verbose_name='Номер паспорта')),
                ('mesto_rab', models.CharField(max_length=200, verbose_name='Место работы')),
                ('staj', models.CharField(max_length=200, verbose_name='Общий стаж')),
                ('ped_staj', models.CharField(max_length=200, verbose_name='Пед. Стаж')),
                ('kate_gor', models.CharField(max_length=200, verbose_name='Категория')),
                ('doljnost', models.CharField(max_length=200, verbose_name='Должность')),
                ('uch_zav', models.CharField(max_length=200, verbose_name='ВО СПО Учебное заведения')),
                ('spec_po_dip', models.CharField(max_length=200, verbose_name='Спец по диплому')),
                ('sroc_ob', models.CharField(max_length=200, verbose_name='Сроки обучения')),
                ('ser_dip', models.CharField(max_length=200, verbose_name='Серия диплома')),
                ('nom_dip', models.CharField(max_length=200, verbose_name='Номер диплота')),
                ('kpk_god_proh', models.CharField(max_length=200, verbose_name='КПК (год прохождения последних КПК)')),
                ('mesto_ob', models.CharField(max_length=200, verbose_name='Место обучения и тема КПК')),
                ('photo', models.ImageField(upload_to='madia', verbose_name='Фото')),
            ],
        ),
    ]
