# Generated by Django 4.1.3 on 2022-12-02 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urus_sosh1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedagog',
            table='user',
        ),
    ]
