# Generated by Django 4.1.3 on 2023-01-05 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urus_sosh1', '0003_category_pedagog_cet'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_uch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klass', models.CharField(max_length=20, verbose_name='Класс')),
                ('foto', models.ImageField(upload_to='media/class', verbose_name='Фото класса')),
                ('klass_ruk', models.CharField(max_length=50, verbose_name='Классный руоводитель')),
            ],
        ),
        migrations.CreateModel(
            name='ucheniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО')),
                ('data', models.CharField(max_length=100, verbose_name='Дата роджения')),
                ('snils', models.CharField(max_length=100, verbose_name='СНИЛС')),
                ('adres', models.CharField(max_length=100, verbose_name='Адрес место жительство')),
                ('fio_ot', models.CharField(max_length=100, verbose_name='ФИО Отца')),
                ('tel_ot', models.CharField(max_length=100, verbose_name='Телефон отца')),
                ('mesto_rab_ot', models.CharField(max_length=100, verbose_name='Место работы отца')),
                ('fio_mat', models.CharField(max_length=100, verbose_name='ФИО Матери')),
                ('tel_mat', models.CharField(max_length=100, verbose_name='Телефон Матери')),
                ('mesto_rab_mat', models.CharField(max_length=100, verbose_name='Место работы Матери')),
                ('foto', models.ImageField(upload_to='media/ucheniki', verbose_name='Фото')),
                ('uch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urus_sosh1.cat_uch')),
            ],
        ),
    ]
