# Generated by Django 4.1.3 on 2023-01-05 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urus_sosh1', '0004_cat_uch_ucheniki'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_uch',
            name='opis_klass',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ucheniki',
            name='uch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urus_sosh1.cat_uch', verbose_name='Класс'),
        ),
    ]
