# Generated by Django 4.1.3 on 2023-01-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urus_sosh1', '0005_cat_uch_opis_klass_alter_ucheniki_uch'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucheniki',
            name='status',
            field=models.CharField(max_length=100, null=True, verbose_name='Социальный статус семьи'),
        ),
    ]
