# Generated by Django 4.1.3 on 2023-01-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urus_sosh1', '0006_ucheniki_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mane', models.CharField(max_length=100, verbose_name='имя')),
                ('docs', models.FileField(upload_to='doks/')),
            ],
        ),
    ]
