# Generated by Django 4.1.3 on 2023-01-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urus_sosh1', '0007_doc'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ucheniki',
            table='urus_sosh1_ucheniki',
        ),
    ]
