# Generated by Django 4.1.3 on 2023-02-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urus_sosh1', '0008_alter_ucheniki_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='doc',
            name='admini',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='urus_sosh1.adminis', verbose_name='Группа'),
        ),
    ]
